#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNhaSach")]
	public partial class QLNhaSachDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaTruc(CaTruc instance);
    partial void UpdateCaTruc(CaTruc instance);
    partial void DeleteCaTruc(CaTruc instance);
    partial void InsertNhaPhanPhoi(NhaPhanPhoi instance);
    partial void UpdateNhaPhanPhoi(NhaPhanPhoi instance);
    partial void DeleteNhaPhanPhoi(NhaPhanPhoi instance);
    partial void InsertChiNhanh(ChiNhanh instance);
    partial void UpdateChiNhanh(ChiNhanh instance);
    partial void DeleteChiNhanh(ChiNhanh instance);
    partial void InsertChiTietCaTruc(ChiTietCaTruc instance);
    partial void UpdateChiTietCaTruc(ChiTietCaTruc instance);
    partial void DeleteChiTietCaTruc(ChiTietCaTruc instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertCTHoaDon(CTHoaDon instance);
    partial void UpdateCTHoaDon(CTHoaDon instance);
    partial void DeleteCTHoaDon(CTHoaDon instance);
    partial void InsertCTKhuyenMai(CTKhuyenMai instance);
    partial void UpdateCTKhuyenMai(CTKhuyenMai instance);
    partial void DeleteCTKhuyenMai(CTKhuyenMai instance);
    partial void InsertDiaChiKhachHang(DiaChiKhachHang instance);
    partial void UpdateDiaChiKhachHang(DiaChiKhachHang instance);
    partial void DeleteDiaChiKhachHang(DiaChiKhachHang instance);
    partial void InsertHangHoa(HangHoa instance);
    partial void UpdateHangHoa(HangHoa instance);
    partial void DeleteHangHoa(HangHoa instance);
    partial void InsertHoaDon(HoaDon instance);
    partial void UpdateHoaDon(HoaDon instance);
    partial void DeleteHoaDon(HoaDon instance);
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertKhuyenMai(KhuyenMai instance);
    partial void UpdateKhuyenMai(KhuyenMai instance);
    partial void DeleteKhuyenMai(KhuyenMai instance);
    partial void InsertLoaiHangHoa(LoaiHangHoa instance);
    partial void UpdateLoaiHangHoa(LoaiHangHoa instance);
    partial void DeleteLoaiHangHoa(LoaiHangHoa instance);
    partial void InsertNhaCCCT(NhaCCCT instance);
    partial void UpdateNhaCCCT(NhaCCCT instance);
    partial void DeleteNhaCCCT(NhaCCCT instance);
    partial void InsertNhanSu(NhanSu instance);
    partial void UpdateNhanSu(NhanSu instance);
    partial void DeleteNhanSu(NhanSu instance);
    #endregion
		
		public QLNhaSachDataContext() : 
				base(global::DAL.Properties.Settings.Default.QLNhaSachConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNhaSachDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaTruc> CaTrucs
		{
			get
			{
				return this.GetTable<CaTruc>();
			}
		}
		
		public System.Data.Linq.Table<NhaPhanPhoi> NhaPhanPhois
		{
			get
			{
				return this.GetTable<NhaPhanPhoi>();
			}
		}
		
		public System.Data.Linq.Table<ChiNhanh> ChiNhanhs
		{
			get
			{
				return this.GetTable<ChiNhanh>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietCaTruc> ChiTietCaTrucs
		{
			get
			{
				return this.GetTable<ChiTietCaTruc>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<CTHoaDon> CTHoaDons
		{
			get
			{
				return this.GetTable<CTHoaDon>();
			}
		}
		
		public System.Data.Linq.Table<CTKhuyenMai> CTKhuyenMais
		{
			get
			{
				return this.GetTable<CTKhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<DiaChiKhachHang> DiaChiKhachHangs
		{
			get
			{
				return this.GetTable<DiaChiKhachHang>();
			}
		}
		
		public System.Data.Linq.Table<HangHoa> HangHoas
		{
			get
			{
				return this.GetTable<HangHoa>();
			}
		}
		
		public System.Data.Linq.Table<HoaDon> HoaDons
		{
			get
			{
				return this.GetTable<HoaDon>();
			}
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<KhuyenMai> KhuyenMais
		{
			get
			{
				return this.GetTable<KhuyenMai>();
			}
		}
		
		public System.Data.Linq.Table<LoaiHangHoa> LoaiHangHoas
		{
			get
			{
				return this.GetTable<LoaiHangHoa>();
			}
		}
		
		public System.Data.Linq.Table<NhaCCCT> NhaCCCTs
		{
			get
			{
				return this.GetTable<NhaCCCT>();
			}
		}
		
		public System.Data.Linq.Table<NhanSu> NhanSus
		{
			get
			{
				return this.GetTable<NhanSu>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaTruc")]
	public partial class CaTruc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCT;
		
		private string _maCN;
		
		private string _tenCaTruc;
		
		private System.Nullable<System.TimeSpan> _gioBD;
		
		private System.Nullable<System.TimeSpan> _gioKT;
		
		private string _ghiChu;
		
		private EntitySet<ChiTietCaTruc> _ChiTietCaTrucs;
		
		private EntityRef<ChiNhanh> _ChiNhanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTChanging(int value);
    partial void OnmaCTChanged();
    partial void OnmaCNChanging(string value);
    partial void OnmaCNChanged();
    partial void OntenCaTrucChanging(string value);
    partial void OntenCaTrucChanged();
    partial void OngioBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioBDChanged();
    partial void OngioKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OngioKTChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public CaTruc()
		{
			this._ChiTietCaTrucs = new EntitySet<ChiTietCaTruc>(new Action<ChiTietCaTruc>(this.attach_ChiTietCaTrucs), new Action<ChiTietCaTruc>(this.detach_ChiTietCaTrucs));
			this._ChiNhanh = default(EntityRef<ChiNhanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCT
		{
			get
			{
				return this._maCT;
			}
			set
			{
				if ((this._maCT != value))
				{
					this.OnmaCTChanging(value);
					this.SendPropertyChanging();
					this._maCT = value;
					this.SendPropertyChanged("maCT");
					this.OnmaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCN", DbType="VarChar(10)")]
		public string maCN
		{
			get
			{
				return this._maCN;
			}
			set
			{
				if ((this._maCN != value))
				{
					if (this._ChiNhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCNChanging(value);
					this.SendPropertyChanging();
					this._maCN = value;
					this.SendPropertyChanged("maCN");
					this.OnmaCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCaTruc", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string tenCaTruc
		{
			get
			{
				return this._tenCaTruc;
			}
			set
			{
				if ((this._tenCaTruc != value))
				{
					this.OntenCaTrucChanging(value);
					this.SendPropertyChanging();
					this._tenCaTruc = value;
					this.SendPropertyChanged("tenCaTruc");
					this.OntenCaTrucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioBD", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioBD
		{
			get
			{
				return this._gioBD;
			}
			set
			{
				if ((this._gioBD != value))
				{
					this.OngioBDChanging(value);
					this.SendPropertyChanging();
					this._gioBD = value;
					this.SendPropertyChanged("gioBD");
					this.OngioBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioKT", DbType="Time")]
		public System.Nullable<System.TimeSpan> gioKT
		{
			get
			{
				return this._gioKT;
			}
			set
			{
				if ((this._gioKT != value))
				{
					this.OngioKTChanging(value);
					this.SendPropertyChanging();
					this._gioKT = value;
					this.SendPropertyChanged("gioKT");
					this.OngioKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaTruc_ChiTietCaTruc", Storage="_ChiTietCaTrucs", ThisKey="maCT", OtherKey="maCT")]
		public EntitySet<ChiTietCaTruc> ChiTietCaTrucs
		{
			get
			{
				return this._ChiTietCaTrucs;
			}
			set
			{
				this._ChiTietCaTrucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_CaTruc", Storage="_ChiNhanh", ThisKey="maCN", OtherKey="maCN", IsForeignKey=true)]
		public ChiNhanh ChiNhanh
		{
			get
			{
				return this._ChiNhanh.Entity;
			}
			set
			{
				ChiNhanh previousValue = this._ChiNhanh.Entity;
				if (((previousValue != value) 
							|| (this._ChiNhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiNhanh.Entity = null;
						previousValue.CaTrucs.Remove(this);
					}
					this._ChiNhanh.Entity = value;
					if ((value != null))
					{
						value.CaTrucs.Add(this);
						this._maCN = value.maCN;
					}
					else
					{
						this._maCN = default(string);
					}
					this.SendPropertyChanged("ChiNhanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietCaTrucs(ChiTietCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.CaTruc = this;
		}
		
		private void detach_ChiTietCaTrucs(ChiTietCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.CaTruc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaPhanPhoi")]
	public partial class NhaPhanPhoi : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNPP;
		
		private string _tenNPP;
		
		private string _diachiNPP;
		
		private string _sdtNPP;
		
		private string _emailNPP;
		
		private EntitySet<HangHoa> _HangHoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNPPChanging(string value);
    partial void OnmaNPPChanged();
    partial void OntenNPPChanging(string value);
    partial void OntenNPPChanged();
    partial void OndiachiNPPChanging(string value);
    partial void OndiachiNPPChanged();
    partial void OnsdtNPPChanging(string value);
    partial void OnsdtNPPChanged();
    partial void OnemailNPPChanging(string value);
    partial void OnemailNPPChanged();
    #endregion
		
		public NhaPhanPhoi()
		{
			this._HangHoas = new EntitySet<HangHoa>(new Action<HangHoa>(this.attach_HangHoas), new Action<HangHoa>(this.detach_HangHoas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNPP", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNPP
		{
			get
			{
				return this._maNPP;
			}
			set
			{
				if ((this._maNPP != value))
				{
					this.OnmaNPPChanging(value);
					this.SendPropertyChanging();
					this._maNPP = value;
					this.SendPropertyChanged("maNPP");
					this.OnmaNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNPP", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tenNPP
		{
			get
			{
				return this._tenNPP;
			}
			set
			{
				if ((this._tenNPP != value))
				{
					this.OntenNPPChanging(value);
					this.SendPropertyChanging();
					this._tenNPP = value;
					this.SendPropertyChanged("tenNPP");
					this.OntenNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiNPP", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diachiNPP
		{
			get
			{
				return this._diachiNPP;
			}
			set
			{
				if ((this._diachiNPP != value))
				{
					this.OndiachiNPPChanging(value);
					this.SendPropertyChanging();
					this._diachiNPP = value;
					this.SendPropertyChanged("diachiNPP");
					this.OndiachiNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtNPP", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdtNPP
		{
			get
			{
				return this._sdtNPP;
			}
			set
			{
				if ((this._sdtNPP != value))
				{
					this.OnsdtNPPChanging(value);
					this.SendPropertyChanging();
					this._sdtNPP = value;
					this.SendPropertyChanged("sdtNPP");
					this.OnsdtNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailNPP", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string emailNPP
		{
			get
			{
				return this._emailNPP;
			}
			set
			{
				if ((this._emailNPP != value))
				{
					this.OnemailNPPChanging(value);
					this.SendPropertyChanging();
					this._emailNPP = value;
					this.SendPropertyChanged("emailNPP");
					this.OnemailNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoi_HangHoa", Storage="_HangHoas", ThisKey="maNPP", OtherKey="maNPP")]
		public EntitySet<HangHoa> HangHoas
		{
			get
			{
				return this._HangHoas;
			}
			set
			{
				this._HangHoas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HangHoas(HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoi = this;
		}
		
		private void detach_HangHoas(HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.NhaPhanPhoi = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiNhanh")]
	public partial class ChiNhanh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maCN;
		
		private string _tenCN;
		
		private string _diaChi;
		
		private string _soDienThoai;
		
		private string _email;
		
		private string _ghiChu;
		
		private EntitySet<CaTruc> _CaTrucs;
		
		private EntitySet<NhanSu> _NhanSus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCNChanging(string value);
    partial void OnmaCNChanged();
    partial void OntenCNChanging(string value);
    partial void OntenCNChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OnsoDienThoaiChanging(string value);
    partial void OnsoDienThoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public ChiNhanh()
		{
			this._CaTrucs = new EntitySet<CaTruc>(new Action<CaTruc>(this.attach_CaTrucs), new Action<CaTruc>(this.detach_CaTrucs));
			this._NhanSus = new EntitySet<NhanSu>(new Action<NhanSu>(this.attach_NhanSus), new Action<NhanSu>(this.detach_NhanSus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCN", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maCN
		{
			get
			{
				return this._maCN;
			}
			set
			{
				if ((this._maCN != value))
				{
					this.OnmaCNChanging(value);
					this.SendPropertyChanging();
					this._maCN = value;
					this.SendPropertyChanged("maCN");
					this.OnmaCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenCN", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string tenCN
		{
			get
			{
				return this._tenCN;
			}
			set
			{
				if ((this._tenCN != value))
				{
					this.OntenCNChanging(value);
					this.SendPropertyChanging();
					this._tenCN = value;
					this.SendPropertyChanged("tenCN");
					this.OntenCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDienThoai", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string soDienThoai
		{
			get
			{
				return this._soDienThoai;
			}
			set
			{
				if ((this._soDienThoai != value))
				{
					this.OnsoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._soDienThoai = value;
					this.SendPropertyChanged("soDienThoai");
					this.OnsoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_CaTruc", Storage="_CaTrucs", ThisKey="maCN", OtherKey="maCN")]
		public EntitySet<CaTruc> CaTrucs
		{
			get
			{
				return this._CaTrucs;
			}
			set
			{
				this._CaTrucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_NhanSu", Storage="_NhanSus", ThisKey="maCN", OtherKey="maCN")]
		public EntitySet<NhanSu> NhanSus
		{
			get
			{
				return this._NhanSus;
			}
			set
			{
				this._NhanSus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CaTrucs(CaTruc entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = this;
		}
		
		private void detach_CaTrucs(CaTruc entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = null;
		}
		
		private void attach_NhanSus(NhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = this;
		}
		
		private void detach_NhanSus(NhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChiNhanh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietCaTruc")]
	public partial class ChiTietCaTruc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCTCT;
		
		private System.Nullable<int> _maCT;
		
		private string _maNS;
		
		private EntityRef<CaTruc> _CaTruc;
		
		private EntityRef<NhanSu> _NhanSu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTCTChanging(int value);
    partial void OnmaCTCTChanged();
    partial void OnmaCTChanging(System.Nullable<int> value);
    partial void OnmaCTChanged();
    partial void OnmaNSChanging(string value);
    partial void OnmaNSChanged();
    #endregion
		
		public ChiTietCaTruc()
		{
			this._CaTruc = default(EntityRef<CaTruc>);
			this._NhanSu = default(EntityRef<NhanSu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTCT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCTCT
		{
			get
			{
				return this._maCTCT;
			}
			set
			{
				if ((this._maCTCT != value))
				{
					this.OnmaCTCTChanging(value);
					this.SendPropertyChanging();
					this._maCTCT = value;
					this.SendPropertyChanged("maCTCT");
					this.OnmaCTCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCT", DbType="Int")]
		public System.Nullable<int> maCT
		{
			get
			{
				return this._maCT;
			}
			set
			{
				if ((this._maCT != value))
				{
					if (this._CaTruc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCTChanging(value);
					this.SendPropertyChanging();
					this._maCT = value;
					this.SendPropertyChanged("maCT");
					this.OnmaCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNS", DbType="VarChar(7)")]
		public string maNS
		{
			get
			{
				return this._maNS;
			}
			set
			{
				if ((this._maNS != value))
				{
					if (this._NhanSu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNSChanging(value);
					this.SendPropertyChanging();
					this._maNS = value;
					this.SendPropertyChanged("maNS");
					this.OnmaNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaTruc_ChiTietCaTruc", Storage="_CaTruc", ThisKey="maCT", OtherKey="maCT", IsForeignKey=true)]
		public CaTruc CaTruc
		{
			get
			{
				return this._CaTruc.Entity;
			}
			set
			{
				CaTruc previousValue = this._CaTruc.Entity;
				if (((previousValue != value) 
							|| (this._CaTruc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaTruc.Entity = null;
						previousValue.ChiTietCaTrucs.Remove(this);
					}
					this._CaTruc.Entity = value;
					if ((value != null))
					{
						value.ChiTietCaTrucs.Add(this);
						this._maCT = value.maCT;
					}
					else
					{
						this._maCT = default(Nullable<int>);
					}
					this.SendPropertyChanged("CaTruc");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanSu_ChiTietCaTruc", Storage="_NhanSu", ThisKey="maNS", OtherKey="maNS", IsForeignKey=true)]
		public NhanSu NhanSu
		{
			get
			{
				return this._NhanSu.Entity;
			}
			set
			{
				NhanSu previousValue = this._NhanSu.Entity;
				if (((previousValue != value) 
							|| (this._NhanSu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanSu.Entity = null;
						previousValue.ChiTietCaTrucs.Remove(this);
					}
					this._NhanSu.Entity = value;
					if ((value != null))
					{
						value.ChiTietCaTrucs.Add(this);
						this._maNS = value.maNS;
					}
					else
					{
						this._maNS = default(string);
					}
					this.SendPropertyChanged("NhanSu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maChucVu;
		
		private string _tenChucVu;
		
		private EntitySet<NhanSu> _NhanSus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChucVuChanging(int value);
    partial void OnmaChucVuChanged();
    partial void OntenChucVuChanging(string value);
    partial void OntenChucVuChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanSus = new EntitySet<NhanSu>(new Action<NhanSu>(this.attach_NhanSus), new Action<NhanSu>(this.detach_NhanSus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maChucVu", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maChucVu
		{
			get
			{
				return this._maChucVu;
			}
			set
			{
				if ((this._maChucVu != value))
				{
					this.OnmaChucVuChanging(value);
					this.SendPropertyChanging();
					this._maChucVu = value;
					this.SendPropertyChanged("maChucVu");
					this.OnmaChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChucVu", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tenChucVu
		{
			get
			{
				return this._tenChucVu;
			}
			set
			{
				if ((this._tenChucVu != value))
				{
					this.OntenChucVuChanging(value);
					this.SendPropertyChanging();
					this._tenChucVu = value;
					this.SendPropertyChanged("tenChucVu");
					this.OntenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanSu", Storage="_NhanSus", ThisKey="maChucVu", OtherKey="chucVu")]
		public EntitySet<NhanSu> NhanSus
		{
			get
			{
				return this._NhanSus;
			}
			set
			{
				this._NhanSus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanSus(NhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu1 = this;
		}
		
		private void detach_NhanSus(NhanSu entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTHoaDon")]
	public partial class CTHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCTHD;
		
		private string _maHD;
		
		private string _maHH;
		
		private System.Nullable<int> _SL;
		
		private EntityRef<HangHoa> _HangHoa;
		
		private EntityRef<HoaDon> _HoaDon;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTHDChanging(int value);
    partial void OnmaCTHDChanged();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaHHChanging(string value);
    partial void OnmaHHChanged();
    partial void OnSLChanging(System.Nullable<int> value);
    partial void OnSLChanged();
    #endregion
		
		public CTHoaDon()
		{
			this._HangHoa = default(EntityRef<HangHoa>);
			this._HoaDon = default(EntityRef<HoaDon>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCTHD
		{
			get
			{
				return this._maCTHD;
			}
			set
			{
				if ((this._maCTHD != value))
				{
					this.OnmaCTHDChanging(value);
					this.SendPropertyChanging();
					this._maCTHD = value;
					this.SendPropertyChanged("maCTHD");
					this.OnmaCTHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					if (this._HoaDon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHH", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHH
		{
			get
			{
				return this._maHH;
			}
			set
			{
				if ((this._maHH != value))
				{
					if (this._HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHHChanging(value);
					this.SendPropertyChanging();
					this._maHH = value;
					this.SendPropertyChanged("maHH");
					this.OnmaHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SL", DbType="Int")]
		public System.Nullable<int> SL
		{
			get
			{
				return this._SL;
			}
			set
			{
				if ((this._SL != value))
				{
					this.OnSLChanging(value);
					this.SendPropertyChanging();
					this._SL = value;
					this.SendPropertyChanged("SL");
					this.OnSLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_CTHoaDon", Storage="_HangHoa", ThisKey="maHH", OtherKey="maHH", IsForeignKey=true)]
		public HangHoa HangHoa
		{
			get
			{
				return this._HangHoa.Entity;
			}
			set
			{
				HangHoa previousValue = this._HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangHoa.Entity = null;
						previousValue.CTHoaDons.Remove(this);
					}
					this._HangHoa.Entity = value;
					if ((value != null))
					{
						value.CTHoaDons.Add(this);
						this._maHH = value.maHH;
					}
					else
					{
						this._maHH = default(string);
					}
					this.SendPropertyChanged("HangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CTHoaDon", Storage="_HoaDon", ThisKey="maHD", OtherKey="maHD", IsForeignKey=true)]
		public HoaDon HoaDon
		{
			get
			{
				return this._HoaDon.Entity;
			}
			set
			{
				HoaDon previousValue = this._HoaDon.Entity;
				if (((previousValue != value) 
							|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDon.Entity = null;
						previousValue.CTHoaDons.Remove(this);
					}
					this._HoaDon.Entity = value;
					if ((value != null))
					{
						value.CTHoaDons.Add(this);
						this._maHD = value.maHD;
					}
					else
					{
						this._maHD = default(string);
					}
					this.SendPropertyChanged("HoaDon");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CTKhuyenMai")]
	public partial class CTKhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCTKM;
		
		private string _maHH;
		
		private string _maKM;
		
		private System.Nullable<System.DateTime> _ngayBD;
		
		private System.Nullable<System.DateTime> _ngayKT;
		
		private EntityRef<HangHoa> _HangHoa;
		
		private EntityRef<KhuyenMai> _KhuyenMai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTKMChanging(int value);
    partial void OnmaCTKMChanged();
    partial void OnmaHHChanging(string value);
    partial void OnmaHHChanged();
    partial void OnmaKMChanging(string value);
    partial void OnmaKMChanged();
    partial void OnngayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnngayBDChanged();
    partial void OnngayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnngayKTChanged();
    #endregion
		
		public CTKhuyenMai()
		{
			this._HangHoa = default(EntityRef<HangHoa>);
			this._KhuyenMai = default(EntityRef<KhuyenMai>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTKM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCTKM
		{
			get
			{
				return this._maCTKM;
			}
			set
			{
				if ((this._maCTKM != value))
				{
					this.OnmaCTKMChanging(value);
					this.SendPropertyChanging();
					this._maCTKM = value;
					this.SendPropertyChanged("maCTKM");
					this.OnmaCTKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHH", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHH
		{
			get
			{
				return this._maHH;
			}
			set
			{
				if ((this._maHH != value))
				{
					if (this._HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHHChanging(value);
					this.SendPropertyChanging();
					this._maHH = value;
					this.SendPropertyChanged("maHH");
					this.OnmaHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKM", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKM
		{
			get
			{
				return this._maKM;
			}
			set
			{
				if ((this._maKM != value))
				{
					if (this._KhuyenMai.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKMChanging(value);
					this.SendPropertyChanging();
					this._maKM = value;
					this.SendPropertyChanged("maKM");
					this.OnmaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayBD
		{
			get
			{
				return this._ngayBD;
			}
			set
			{
				if ((this._ngayBD != value))
				{
					this.OnngayBDChanging(value);
					this.SendPropertyChanging();
					this._ngayBD = value;
					this.SendPropertyChanged("ngayBD");
					this.OnngayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayKT
		{
			get
			{
				return this._ngayKT;
			}
			set
			{
				if ((this._ngayKT != value))
				{
					this.OnngayKTChanging(value);
					this.SendPropertyChanging();
					this._ngayKT = value;
					this.SendPropertyChanged("ngayKT");
					this.OnngayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_CTKhuyenMai", Storage="_HangHoa", ThisKey="maHH", OtherKey="maHH", IsForeignKey=true)]
		public HangHoa HangHoa
		{
			get
			{
				return this._HangHoa.Entity;
			}
			set
			{
				HangHoa previousValue = this._HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangHoa.Entity = null;
						previousValue.CTKhuyenMais.Remove(this);
					}
					this._HangHoa.Entity = value;
					if ((value != null))
					{
						value.CTKhuyenMais.Add(this);
						this._maHH = value.maHH;
					}
					else
					{
						this._maHH = default(string);
					}
					this.SendPropertyChanged("HangHoa");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_CTKhuyenMai", Storage="_KhuyenMai", ThisKey="maKM", OtherKey="maKM", IsForeignKey=true)]
		public KhuyenMai KhuyenMai
		{
			get
			{
				return this._KhuyenMai.Entity;
			}
			set
			{
				KhuyenMai previousValue = this._KhuyenMai.Entity;
				if (((previousValue != value) 
							|| (this._KhuyenMai.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhuyenMai.Entity = null;
						previousValue.CTKhuyenMais.Remove(this);
					}
					this._KhuyenMai.Entity = value;
					if ((value != null))
					{
						value.CTKhuyenMais.Add(this);
						this._maKM = value.maKM;
					}
					else
					{
						this._maKM = default(string);
					}
					this.SendPropertyChanged("KhuyenMai");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaChiKhachHang")]
	public partial class DiaChiKhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madiachiKH;
		
		private string _maKH;
		
		private string _diachiKH;
		
		private EntityRef<KhachHang> _KhachHang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadiachiKHChanging(string value);
    partial void OnmadiachiKHChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OndiachiKHChanging(string value);
    partial void OndiachiKHChanged();
    #endregion
		
		public DiaChiKhachHang()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madiachiKH", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madiachiKH
		{
			get
			{
				return this._madiachiKH;
			}
			set
			{
				if ((this._madiachiKH != value))
				{
					this.OnmadiachiKHChanging(value);
					this.SendPropertyChanging();
					this._madiachiKH = value;
					this.SendPropertyChanged("madiachiKH");
					this.OnmadiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(11)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiKH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string diachiKH
		{
			get
			{
				return this._diachiKH;
			}
			set
			{
				if ((this._diachiKH != value))
				{
					this.OndiachiKHChanging(value);
					this.SendPropertyChanging();
					this._diachiKH = value;
					this.SendPropertyChanged("diachiKH");
					this.OndiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DiaChiKhachHang", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.DiaChiKhachHangs.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.DiaChiKhachHangs.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HangHoa")]
	public partial class HangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHH;
		
		private string _maLHH;
		
		private string _tenHH;
		
		private int _giaHH;
		
		private string _donViTinh;
		
		private int _soLuongTon;
		
		private string _maNPP;
		
		private System.Nullable<int> _hanSD;
		
		private string _moTa;
		
		private string _ghiChu;
		
		private string _tinhTrang;
		
		private EntitySet<CTHoaDon> _CTHoaDons;
		
		private EntitySet<CTKhuyenMai> _CTKhuyenMais;
		
		private EntitySet<NhaCCCT> _NhaCCCTs;
		
		private EntityRef<NhaPhanPhoi> _NhaPhanPhoi;
		
		private EntityRef<LoaiHangHoa> _LoaiHangHoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHHChanging(string value);
    partial void OnmaHHChanged();
    partial void OnmaLHHChanging(string value);
    partial void OnmaLHHChanged();
    partial void OntenHHChanging(string value);
    partial void OntenHHChanged();
    partial void OngiaHHChanging(int value);
    partial void OngiaHHChanged();
    partial void OndonViTinhChanging(string value);
    partial void OndonViTinhChanged();
    partial void OnsoLuongTonChanging(int value);
    partial void OnsoLuongTonChanged();
    partial void OnmaNPPChanging(string value);
    partial void OnmaNPPChanged();
    partial void OnhanSDChanging(System.Nullable<int> value);
    partial void OnhanSDChanged();
    partial void OnmoTaChanging(string value);
    partial void OnmoTaChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OntinhTrangChanging(string value);
    partial void OntinhTrangChanged();
    #endregion
		
		public HangHoa()
		{
			this._CTHoaDons = new EntitySet<CTHoaDon>(new Action<CTHoaDon>(this.attach_CTHoaDons), new Action<CTHoaDon>(this.detach_CTHoaDons));
			this._CTKhuyenMais = new EntitySet<CTKhuyenMai>(new Action<CTKhuyenMai>(this.attach_CTKhuyenMais), new Action<CTKhuyenMai>(this.detach_CTKhuyenMais));
			this._NhaCCCTs = new EntitySet<NhaCCCT>(new Action<NhaCCCT>(this.attach_NhaCCCTs), new Action<NhaCCCT>(this.detach_NhaCCCTs));
			this._NhaPhanPhoi = default(EntityRef<NhaPhanPhoi>);
			this._LoaiHangHoa = default(EntityRef<LoaiHangHoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHH", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHH
		{
			get
			{
				return this._maHH;
			}
			set
			{
				if ((this._maHH != value))
				{
					this.OnmaHHChanging(value);
					this.SendPropertyChanging();
					this._maHH = value;
					this.SendPropertyChanged("maHH");
					this.OnmaHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLHH", DbType="VarChar(5)")]
		public string maLHH
		{
			get
			{
				return this._maLHH;
			}
			set
			{
				if ((this._maLHH != value))
				{
					if (this._LoaiHangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaLHHChanging(value);
					this.SendPropertyChanging();
					this._maLHH = value;
					this.SendPropertyChanged("maLHH");
					this.OnmaLHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenHH", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string tenHH
		{
			get
			{
				return this._tenHH;
			}
			set
			{
				if ((this._tenHH != value))
				{
					this.OntenHHChanging(value);
					this.SendPropertyChanging();
					this._tenHH = value;
					this.SendPropertyChanged("tenHH");
					this.OntenHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giaHH", DbType="Int NOT NULL")]
		public int giaHH
		{
			get
			{
				return this._giaHH;
			}
			set
			{
				if ((this._giaHH != value))
				{
					this.OngiaHHChanging(value);
					this.SendPropertyChanging();
					this._giaHH = value;
					this.SendPropertyChanged("giaHH");
					this.OngiaHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donViTinh", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string donViTinh
		{
			get
			{
				return this._donViTinh;
			}
			set
			{
				if ((this._donViTinh != value))
				{
					this.OndonViTinhChanging(value);
					this.SendPropertyChanging();
					this._donViTinh = value;
					this.SendPropertyChanged("donViTinh");
					this.OndonViTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongTon", DbType="Int NOT NULL")]
		public int soLuongTon
		{
			get
			{
				return this._soLuongTon;
			}
			set
			{
				if ((this._soLuongTon != value))
				{
					this.OnsoLuongTonChanging(value);
					this.SendPropertyChanging();
					this._soLuongTon = value;
					this.SendPropertyChanged("soLuongTon");
					this.OnsoLuongTonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNPP", DbType="VarChar(11)")]
		public string maNPP
		{
			get
			{
				return this._maNPP;
			}
			set
			{
				if ((this._maNPP != value))
				{
					if (this._NhaPhanPhoi.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNPPChanging(value);
					this.SendPropertyChanging();
					this._maNPP = value;
					this.SendPropertyChanged("maNPP");
					this.OnmaNPPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hanSD", DbType="Int")]
		public System.Nullable<int> hanSD
		{
			get
			{
				return this._hanSD;
			}
			set
			{
				if ((this._hanSD != value))
				{
					this.OnhanSDChanging(value);
					this.SendPropertyChanging();
					this._hanSD = value;
					this.SendPropertyChanged("hanSD");
					this.OnhanSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_moTa", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string moTa
		{
			get
			{
				return this._moTa;
			}
			set
			{
				if ((this._moTa != value))
				{
					this.OnmoTaChanging(value);
					this.SendPropertyChanging();
					this._moTa = value;
					this.SendPropertyChanged("moTa");
					this.OnmoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrang", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string tinhTrang
		{
			get
			{
				return this._tinhTrang;
			}
			set
			{
				if ((this._tinhTrang != value))
				{
					this.OntinhTrangChanging(value);
					this.SendPropertyChanging();
					this._tinhTrang = value;
					this.SendPropertyChanged("tinhTrang");
					this.OntinhTrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_CTHoaDon", Storage="_CTHoaDons", ThisKey="maHH", OtherKey="maHH")]
		public EntitySet<CTHoaDon> CTHoaDons
		{
			get
			{
				return this._CTHoaDons;
			}
			set
			{
				this._CTHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_CTKhuyenMai", Storage="_CTKhuyenMais", ThisKey="maHH", OtherKey="maHH")]
		public EntitySet<CTKhuyenMai> CTKhuyenMais
		{
			get
			{
				return this._CTKhuyenMais;
			}
			set
			{
				this._CTKhuyenMais.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_NhaCCCT", Storage="_NhaCCCTs", ThisKey="maHH", OtherKey="maHH")]
		public EntitySet<NhaCCCT> NhaCCCTs
		{
			get
			{
				return this._NhaCCCTs;
			}
			set
			{
				this._NhaCCCTs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhaPhanPhoi_HangHoa", Storage="_NhaPhanPhoi", ThisKey="maNPP", OtherKey="maNPP", IsForeignKey=true)]
		public NhaPhanPhoi NhaPhanPhoi
		{
			get
			{
				return this._NhaPhanPhoi.Entity;
			}
			set
			{
				NhaPhanPhoi previousValue = this._NhaPhanPhoi.Entity;
				if (((previousValue != value) 
							|| (this._NhaPhanPhoi.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhaPhanPhoi.Entity = null;
						previousValue.HangHoas.Remove(this);
					}
					this._NhaPhanPhoi.Entity = value;
					if ((value != null))
					{
						value.HangHoas.Add(this);
						this._maNPP = value.maNPP;
					}
					else
					{
						this._maNPP = default(string);
					}
					this.SendPropertyChanged("NhaPhanPhoi");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHangHoa_HangHoa", Storage="_LoaiHangHoa", ThisKey="maLHH", OtherKey="maLHH", IsForeignKey=true)]
		public LoaiHangHoa LoaiHangHoa
		{
			get
			{
				return this._LoaiHangHoa.Entity;
			}
			set
			{
				LoaiHangHoa previousValue = this._LoaiHangHoa.Entity;
				if (((previousValue != value) 
							|| (this._LoaiHangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LoaiHangHoa.Entity = null;
						previousValue.HangHoas.Remove(this);
					}
					this._LoaiHangHoa.Entity = value;
					if ((value != null))
					{
						value.HangHoas.Add(this);
						this._maLHH = value.maLHH;
					}
					else
					{
						this._maLHH = default(string);
					}
					this.SendPropertyChanged("LoaiHangHoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDons(CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = this;
		}
		
		private void detach_CTHoaDons(CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = null;
		}
		
		private void attach_CTKhuyenMais(CTKhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = this;
		}
		
		private void detach_CTKhuyenMais(CTKhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = null;
		}
		
		private void attach_NhaCCCTs(NhaCCCT entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = this;
		}
		
		private void detach_NhaCCCTs(NhaCCCT entity)
		{
			this.SendPropertyChanging();
			entity.HangHoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
	public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maHD;
		
		private string _maNS;
		
		private string _maKH;
		
		private System.Nullable<double> _donGia;
		
		private System.DateTime _ngayIn;
		
		private string _ghiChu;
		
		private EntitySet<CTHoaDon> _CTHoaDons;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<NhanSu> _NhanSu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaHDChanging(string value);
    partial void OnmaHDChanged();
    partial void OnmaNSChanging(string value);
    partial void OnmaNSChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OndonGiaChanging(System.Nullable<double> value);
    partial void OndonGiaChanged();
    partial void OnngayInChanging(System.DateTime value);
    partial void OnngayInChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public HoaDon()
		{
			this._CTHoaDons = new EntitySet<CTHoaDon>(new Action<CTHoaDon>(this.attach_CTHoaDons), new Action<CTHoaDon>(this.detach_CTHoaDons));
			this._KhachHang = default(EntityRef<KhachHang>);
			this._NhanSu = default(EntityRef<NhanSu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHD", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHD
		{
			get
			{
				return this._maHD;
			}
			set
			{
				if ((this._maHD != value))
				{
					this.OnmaHDChanging(value);
					this.SendPropertyChanging();
					this._maHD = value;
					this.SendPropertyChanged("maHD");
					this.OnmaHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNS", DbType="VarChar(7)")]
		public string maNS
		{
			get
			{
				return this._maNS;
			}
			set
			{
				if ((this._maNS != value))
				{
					if (this._NhanSu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaNSChanging(value);
					this.SendPropertyChanging();
					this._maNS = value;
					this.SendPropertyChanged("maNS");
					this.OnmaNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(11)")]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_donGia", DbType="Float")]
		public System.Nullable<double> donGia
		{
			get
			{
				return this._donGia;
			}
			set
			{
				if ((this._donGia != value))
				{
					this.OndonGiaChanging(value);
					this.SendPropertyChanging();
					this._donGia = value;
					this.SendPropertyChanged("donGia");
					this.OndonGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayIn", DbType="Date NOT NULL")]
		public System.DateTime ngayIn
		{
			get
			{
				return this._ngayIn;
			}
			set
			{
				if ((this._ngayIn != value))
				{
					this.OnngayInChanging(value);
					this.SendPropertyChanging();
					this._ngayIn = value;
					this.SendPropertyChanged("ngayIn");
					this.OnngayInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_CTHoaDon", Storage="_CTHoaDons", ThisKey="maHD", OtherKey="maHD")]
		public EntitySet<CTHoaDon> CTHoaDons
		{
			get
			{
				return this._CTHoaDons;
			}
			set
			{
				this._CTHoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanSu_HoaDon", Storage="_NhanSu", ThisKey="maNS", OtherKey="maNS", IsForeignKey=true)]
		public NhanSu NhanSu
		{
			get
			{
				return this._NhanSu.Entity;
			}
			set
			{
				NhanSu previousValue = this._NhanSu.Entity;
				if (((previousValue != value) 
							|| (this._NhanSu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanSu.Entity = null;
						previousValue.HoaDons.Remove(this);
					}
					this._NhanSu.Entity = value;
					if ((value != null))
					{
						value.HoaDons.Add(this);
						this._maNS = value.maNS;
					}
					else
					{
						this._maNS = default(string);
					}
					this.SendPropertyChanged("NhanSu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTHoaDons(CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = this;
		}
		
		private void detach_CTHoaDons(CTHoaDon entity)
		{
			this.SendPropertyChanging();
			entity.HoaDon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _hoTenKH;
		
		private System.Nullable<System.DateTime> _ngaysinhKH;
		
		private string _gioitinhKH;
		
		private string _diachiKH;
		
		private string _sdtKH;
		
		private string _emailKH;
		
		private EntitySet<DiaChiKhachHang> _DiaChiKhachHangs;
		
		private EntitySet<HoaDon> _HoaDons;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnhoTenKHChanging(string value);
    partial void OnhoTenKHChanged();
    partial void OnngaysinhKHChanging(System.Nullable<System.DateTime> value);
    partial void OnngaysinhKHChanged();
    partial void OngioitinhKHChanging(string value);
    partial void OngioitinhKHChanged();
    partial void OndiachiKHChanging(string value);
    partial void OndiachiKHChanged();
    partial void OnsdtKHChanging(string value);
    partial void OnsdtKHChanged();
    partial void OnemailKHChanging(string value);
    partial void OnemailKHChanged();
    #endregion
		
		public KhachHang()
		{
			this._DiaChiKhachHangs = new EntitySet<DiaChiKhachHang>(new Action<DiaChiKhachHang>(this.attach_DiaChiKhachHangs), new Action<DiaChiKhachHang>(this.detach_DiaChiKhachHangs));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTenKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoTenKH
		{
			get
			{
				return this._hoTenKH;
			}
			set
			{
				if ((this._hoTenKH != value))
				{
					this.OnhoTenKHChanging(value);
					this.SendPropertyChanging();
					this._hoTenKH = value;
					this.SendPropertyChanged("hoTenKH");
					this.OnhoTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinhKH", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngaysinhKH
		{
			get
			{
				return this._ngaysinhKH;
			}
			set
			{
				if ((this._ngaysinhKH != value))
				{
					this.OnngaysinhKHChanging(value);
					this.SendPropertyChanging();
					this._ngaysinhKH = value;
					this.SendPropertyChanged("ngaysinhKH");
					this.OnngaysinhKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinhKH", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioitinhKH
		{
			get
			{
				return this._gioitinhKH;
			}
			set
			{
				if ((this._gioitinhKH != value))
				{
					this.OngioitinhKHChanging(value);
					this.SendPropertyChanging();
					this._gioitinhKH = value;
					this.SendPropertyChanged("gioitinhKH");
					this.OngioitinhKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachiKH", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string diachiKH
		{
			get
			{
				return this._diachiKH;
			}
			set
			{
				if ((this._diachiKH != value))
				{
					this.OndiachiKHChanging(value);
					this.SendPropertyChanging();
					this._diachiKH = value;
					this.SendPropertyChanged("diachiKH");
					this.OndiachiKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtKH", DbType="VarChar(12) NOT NULL", CanBeNull=false)]
		public string sdtKH
		{
			get
			{
				return this._sdtKH;
			}
			set
			{
				if ((this._sdtKH != value))
				{
					this.OnsdtKHChanging(value);
					this.SendPropertyChanging();
					this._sdtKH = value;
					this.SendPropertyChanged("sdtKH");
					this.OnsdtKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailKH", DbType="VarChar(50)")]
		public string emailKH
		{
			get
			{
				return this._emailKH;
			}
			set
			{
				if ((this._emailKH != value))
				{
					this.OnemailKHChanging(value);
					this.SendPropertyChanging();
					this._emailKH = value;
					this.SendPropertyChanged("emailKH");
					this.OnemailKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_DiaChiKhachHang", Storage="_DiaChiKhachHangs", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<DiaChiKhachHang> DiaChiKhachHangs
		{
			get
			{
				return this._DiaChiKhachHangs;
			}
			set
			{
				this._DiaChiKhachHangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_HoaDon", Storage="_HoaDons", ThisKey="maKH", OtherKey="maKH")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_DiaChiKhachHangs(DiaChiKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_DiaChiKhachHangs(DiaChiKhachHang entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
	public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKM;
		
		private string _tenKM;
		
		private System.Nullable<int> _giamGia;
		
		private EntitySet<CTKhuyenMai> _CTKhuyenMais;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKMChanging(string value);
    partial void OnmaKMChanged();
    partial void OntenKMChanging(string value);
    partial void OntenKMChanged();
    partial void OngiamGiaChanging(System.Nullable<int> value);
    partial void OngiamGiaChanged();
    #endregion
		
		public KhuyenMai()
		{
			this._CTKhuyenMais = new EntitySet<CTKhuyenMai>(new Action<CTKhuyenMai>(this.attach_CTKhuyenMais), new Action<CTKhuyenMai>(this.detach_CTKhuyenMais));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKM", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maKM
		{
			get
			{
				return this._maKM;
			}
			set
			{
				if ((this._maKM != value))
				{
					this.OnmaKMChanging(value);
					this.SendPropertyChanging();
					this._maKM = value;
					this.SendPropertyChanged("maKM");
					this.OnmaKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenKM", DbType="NVarChar(50)")]
		public string tenKM
		{
			get
			{
				return this._tenKM;
			}
			set
			{
				if ((this._tenKM != value))
				{
					this.OntenKMChanging(value);
					this.SendPropertyChanging();
					this._tenKM = value;
					this.SendPropertyChanged("tenKM");
					this.OntenKMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giamGia", DbType="Int")]
		public System.Nullable<int> giamGia
		{
			get
			{
				return this._giamGia;
			}
			set
			{
				if ((this._giamGia != value))
				{
					this.OngiamGiaChanging(value);
					this.SendPropertyChanging();
					this._giamGia = value;
					this.SendPropertyChanged("giamGia");
					this.OngiamGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhuyenMai_CTKhuyenMai", Storage="_CTKhuyenMais", ThisKey="maKM", OtherKey="maKM")]
		public EntitySet<CTKhuyenMai> CTKhuyenMais
		{
			get
			{
				return this._CTKhuyenMais;
			}
			set
			{
				this._CTKhuyenMais.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CTKhuyenMais(CTKhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = this;
		}
		
		private void detach_CTKhuyenMais(CTKhuyenMai entity)
		{
			this.SendPropertyChanging();
			entity.KhuyenMai = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LoaiHangHoa")]
	public partial class LoaiHangHoa : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maLHH;
		
		private string _tenLHH;
		
		private string _ghiChu;
		
		private EntitySet<HangHoa> _HangHoas;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaLHHChanging(string value);
    partial void OnmaLHHChanged();
    partial void OntenLHHChanging(string value);
    partial void OntenLHHChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public LoaiHangHoa()
		{
			this._HangHoas = new EntitySet<HangHoa>(new Action<HangHoa>(this.attach_HangHoas), new Action<HangHoa>(this.detach_HangHoas));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maLHH", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maLHH
		{
			get
			{
				return this._maLHH;
			}
			set
			{
				if ((this._maLHH != value))
				{
					this.OnmaLHHChanging(value);
					this.SendPropertyChanging();
					this._maLHH = value;
					this.SendPropertyChanged("maLHH");
					this.OnmaLHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenLHH", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string tenLHH
		{
			get
			{
				return this._tenLHH;
			}
			set
			{
				if ((this._tenLHH != value))
				{
					this.OntenLHHChanging(value);
					this.SendPropertyChanging();
					this._tenLHH = value;
					this.SendPropertyChanged("tenLHH");
					this.OntenLHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LoaiHangHoa_HangHoa", Storage="_HangHoas", ThisKey="maLHH", OtherKey="maLHH")]
		public EntitySet<HangHoa> HangHoas
		{
			get
			{
				return this._HangHoas;
			}
			set
			{
				this._HangHoas.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HangHoas(HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHangHoa = this;
		}
		
		private void detach_HangHoas(HangHoa entity)
		{
			this.SendPropertyChanging();
			entity.LoaiHangHoa = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhaCCCT")]
	public partial class NhaCCCT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _maCTNCC;
		
		private string _maHH;
		
		private System.Nullable<System.DateTime> _ngayCC;
		
		private System.Nullable<int> _soLuong;
		
		private string _ghiChu;
		
		private EntityRef<HangHoa> _HangHoa;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaCTNCCChanging(int value);
    partial void OnmaCTNCCChanged();
    partial void OnmaHHChanging(string value);
    partial void OnmaHHChanged();
    partial void OnngayCCChanging(System.Nullable<System.DateTime> value);
    partial void OnngayCCChanged();
    partial void OnsoLuongChanging(System.Nullable<int> value);
    partial void OnsoLuongChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    #endregion
		
		public NhaCCCT()
		{
			this._HangHoa = default(EntityRef<HangHoa>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCTNCC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int maCTNCC
		{
			get
			{
				return this._maCTNCC;
			}
			set
			{
				if ((this._maCTNCC != value))
				{
					this.OnmaCTNCCChanging(value);
					this.SendPropertyChanging();
					this._maCTNCC = value;
					this.SendPropertyChanged("maCTNCC");
					this.OnmaCTNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maHH", DbType="VarChar(13) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maHH
		{
			get
			{
				return this._maHH;
			}
			set
			{
				if ((this._maHH != value))
				{
					if (this._HangHoa.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaHHChanging(value);
					this.SendPropertyChanging();
					this._maHH = value;
					this.SendPropertyChanged("maHH");
					this.OnmaHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayCC", DbType="DateTime")]
		public System.Nullable<System.DateTime> ngayCC
		{
			get
			{
				return this._ngayCC;
			}
			set
			{
				if ((this._ngayCC != value))
				{
					this.OnngayCCChanging(value);
					this.SendPropertyChanging();
					this._ngayCC = value;
					this.SendPropertyChanged("ngayCC");
					this.OnngayCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuong", DbType="Int")]
		public System.Nullable<int> soLuong
		{
			get
			{
				return this._soLuong;
			}
			set
			{
				if ((this._soLuong != value))
				{
					this.OnsoLuongChanging(value);
					this.SendPropertyChanging();
					this._soLuong = value;
					this.SendPropertyChanged("soLuong");
					this.OnsoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(200)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HangHoa_NhaCCCT", Storage="_HangHoa", ThisKey="maHH", OtherKey="maHH", IsForeignKey=true)]
		public HangHoa HangHoa
		{
			get
			{
				return this._HangHoa.Entity;
			}
			set
			{
				HangHoa previousValue = this._HangHoa.Entity;
				if (((previousValue != value) 
							|| (this._HangHoa.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HangHoa.Entity = null;
						previousValue.NhaCCCTs.Remove(this);
					}
					this._HangHoa.Entity = value;
					if ((value != null))
					{
						value.NhaCCCTs.Add(this);
						this._maHH = value.maHH;
					}
					else
					{
						this._maHH = default(string);
					}
					this.SendPropertyChanged("HangHoa");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanSu")]
	public partial class NhanSu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maNS;
		
		private string _tenNS;
		
		private string _gioiTinh;
		
		private string _cccdNS;
		
		private string _sdtNV;
		
		private string _emailNV;
		
		private string _diaChiNha;
		
		private string _maCN;
		
		private System.Nullable<int> _chucVu;
		
		private string _matkhau;
		
		private EntitySet<ChiTietCaTruc> _ChiTietCaTrucs;
		
		private EntitySet<HoaDon> _HoaDons;
		
		private EntityRef<ChucVu> _ChucVu1;
		
		private EntityRef<ChiNhanh> _ChiNhanh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaNSChanging(string value);
    partial void OnmaNSChanged();
    partial void OntenNSChanging(string value);
    partial void OntenNSChanged();
    partial void OngioiTinhChanging(string value);
    partial void OngioiTinhChanged();
    partial void OncccdNSChanging(string value);
    partial void OncccdNSChanged();
    partial void OnsdtNVChanging(string value);
    partial void OnsdtNVChanged();
    partial void OnemailNVChanging(string value);
    partial void OnemailNVChanged();
    partial void OndiaChiNhaChanging(string value);
    partial void OndiaChiNhaChanged();
    partial void OnmaCNChanging(string value);
    partial void OnmaCNChanged();
    partial void OnchucVuChanging(System.Nullable<int> value);
    partial void OnchucVuChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    #endregion
		
		public NhanSu()
		{
			this._ChiTietCaTrucs = new EntitySet<ChiTietCaTruc>(new Action<ChiTietCaTruc>(this.attach_ChiTietCaTrucs), new Action<ChiTietCaTruc>(this.detach_ChiTietCaTrucs));
			this._HoaDons = new EntitySet<HoaDon>(new Action<HoaDon>(this.attach_HoaDons), new Action<HoaDon>(this.detach_HoaDons));
			this._ChucVu1 = default(EntityRef<ChucVu>);
			this._ChiNhanh = default(EntityRef<ChiNhanh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maNS", DbType="VarChar(7) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maNS
		{
			get
			{
				return this._maNS;
			}
			set
			{
				if ((this._maNS != value))
				{
					this.OnmaNSChanging(value);
					this.SendPropertyChanging();
					this._maNS = value;
					this.SendPropertyChanged("maNS");
					this.OnmaNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenNS", DbType="NVarChar(45) NOT NULL", CanBeNull=false)]
		public string tenNS
		{
			get
			{
				return this._tenNS;
			}
			set
			{
				if ((this._tenNS != value))
				{
					this.OntenNSChanging(value);
					this.SendPropertyChanging();
					this._tenNS = value;
					this.SendPropertyChanged("tenNS");
					this.OntenNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioiTinh", DbType="NVarChar(3) NOT NULL", CanBeNull=false)]
		public string gioiTinh
		{
			get
			{
				return this._gioiTinh;
			}
			set
			{
				if ((this._gioiTinh != value))
				{
					this.OngioiTinhChanging(value);
					this.SendPropertyChanging();
					this._gioiTinh = value;
					this.SendPropertyChanged("gioiTinh");
					this.OngioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccdNS", DbType="NVarChar(11) NOT NULL", CanBeNull=false)]
		public string cccdNS
		{
			get
			{
				return this._cccdNS;
			}
			set
			{
				if ((this._cccdNS != value))
				{
					this.OncccdNSChanging(value);
					this.SendPropertyChanging();
					this._cccdNS = value;
					this.SendPropertyChanged("cccdNS");
					this.OncccdNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtNV", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sdtNV
		{
			get
			{
				return this._sdtNV;
			}
			set
			{
				if ((this._sdtNV != value))
				{
					this.OnsdtNVChanging(value);
					this.SendPropertyChanging();
					this._sdtNV = value;
					this.SendPropertyChanged("sdtNV");
					this.OnsdtNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailNV", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string emailNV
		{
			get
			{
				return this._emailNV;
			}
			set
			{
				if ((this._emailNV != value))
				{
					this.OnemailNVChanging(value);
					this.SendPropertyChanging();
					this._emailNV = value;
					this.SendPropertyChanged("emailNV");
					this.OnemailNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiNha", DbType="NVarChar(55)")]
		public string diaChiNha
		{
			get
			{
				return this._diaChiNha;
			}
			set
			{
				if ((this._diaChiNha != value))
				{
					this.OndiaChiNhaChanging(value);
					this.SendPropertyChanging();
					this._diaChiNha = value;
					this.SendPropertyChanged("diaChiNha");
					this.OndiaChiNhaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCN", DbType="VarChar(10)")]
		public string maCN
		{
			get
			{
				return this._maCN;
			}
			set
			{
				if ((this._maCN != value))
				{
					if (this._ChiNhanh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaCNChanging(value);
					this.SendPropertyChanging();
					this._maCN = value;
					this.SendPropertyChanged("maCN");
					this.OnmaCNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucVu", DbType="Int")]
		public System.Nullable<int> chucVu
		{
			get
			{
				return this._chucVu;
			}
			set
			{
				if ((this._chucVu != value))
				{
					if (this._ChucVu1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnchucVuChanging(value);
					this.SendPropertyChanging();
					this._chucVu = value;
					this.SendPropertyChanged("chucVu");
					this.OnchucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanSu_ChiTietCaTruc", Storage="_ChiTietCaTrucs", ThisKey="maNS", OtherKey="maNS")]
		public EntitySet<ChiTietCaTruc> ChiTietCaTrucs
		{
			get
			{
				return this._ChiTietCaTrucs;
			}
			set
			{
				this._ChiTietCaTrucs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanSu_HoaDon", Storage="_HoaDons", ThisKey="maNS", OtherKey="maNS")]
		public EntitySet<HoaDon> HoaDons
		{
			get
			{
				return this._HoaDons;
			}
			set
			{
				this._HoaDons.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanSu", Storage="_ChucVu1", ThisKey="chucVu", OtherKey="maChucVu", IsForeignKey=true)]
		public ChucVu ChucVu1
		{
			get
			{
				return this._ChucVu1.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu1.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu1.Entity = null;
						previousValue.NhanSus.Remove(this);
					}
					this._ChucVu1.Entity = value;
					if ((value != null))
					{
						value.NhanSus.Add(this);
						this._chucVu = value.maChucVu;
					}
					else
					{
						this._chucVu = default(Nullable<int>);
					}
					this.SendPropertyChanged("ChucVu1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChiNhanh_NhanSu", Storage="_ChiNhanh", ThisKey="maCN", OtherKey="maCN", IsForeignKey=true)]
		public ChiNhanh ChiNhanh
		{
			get
			{
				return this._ChiNhanh.Entity;
			}
			set
			{
				ChiNhanh previousValue = this._ChiNhanh.Entity;
				if (((previousValue != value) 
							|| (this._ChiNhanh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiNhanh.Entity = null;
						previousValue.NhanSus.Remove(this);
					}
					this._ChiNhanh.Entity = value;
					if ((value != null))
					{
						value.NhanSus.Add(this);
						this._maCN = value.maCN;
					}
					else
					{
						this._maCN = default(string);
					}
					this.SendPropertyChanged("ChiNhanh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietCaTrucs(ChiTietCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.NhanSu = this;
		}
		
		private void detach_ChiTietCaTrucs(ChiTietCaTruc entity)
		{
			this.SendPropertyChanging();
			entity.NhanSu = null;
		}
		
		private void attach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanSu = this;
		}
		
		private void detach_HoaDons(HoaDon entity)
		{
			this.SendPropertyChanging();
			entity.NhanSu = null;
		}
	}
}
#pragma warning restore 1591
